# Odinal Encoding

## Importing of libs

In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("customer.csv")
df.sample(7)

    age  gender   review education purchased
11   74    Male     Good        UG       Yes
5    31  Female  Average    School       Yes
44   77  Female  Average        UG        No
30   73    Male  Average        UG        No
39   76    Male     Poor        PG        No
22   18  Female     Poor        PG       Yes
18   19    Male     Good    School        No

In [3]:
d=df.iloc[:,2:]
d.head(5)

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [4]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split (d.iloc[:,:2],d.iloc[:,-1],test_size=0.3)

### Data vidualization of the traain set

In [5]:
x_train,"-----------",y_train

(     review education
 0   Average    School
 9      Good        UG
 28     Poor    School
 31     Poor    School
 24  Average        PG
 3      Good        PG
 27     Poor        PG
 41     Good        PG
 29  Average        UG
 17     Poor        UG
 35     Poor    School
 11     Good        UG
 48     Good        UG
 39     Poor        PG
 14     Poor        PG
 13  Average    School
 47     Good        PG
 22     Poor        PG
 2      Good        PG
 4   Average        UG
 40     Good    School
 20  Average    School
 8   Average        UG
 6      Good    School
 7      Poor    School
 38     Good    School
 21  Average        PG
 19     Poor        PG
 1      Poor        UG
 30  Average        UG
 18     Good    School
 26     Poor        PG
 37  Average        PG
 49     Good        UG
 34  Average    School,
 '-----------',
 0      No
 9     Yes
 28     No
 31    Yes
 24    Yes
 3      No
 27     No
 41    Yes
 29    Yes
 17    Yes
 35    Yes
 11    Yes
 48    Yes
 39     No
 14    Yes
 13     No
 47    Yes
 22    Yes
 2      No
 4      No
 40     No
 20    Yes
 8      No
 6      No
 7     Yes
 38     No
 21     No
 19    Yes
 1      No
 30     No
 18     No
 26     No
 37    Yes
 49     No
 34     No
 Name: purchased, dtype: object)

### Data visulation of the test set

In [6]:
x_test,"-----------",y_test

(     review education
 12     Poor    School
 46     Poor        PG
 5   Average    School
 45     Poor        PG
 16     Poor        UG
 23     Good    School
 10     Good        UG
 43     Poor        PG
 33     Good        PG
 42     Good        PG
 44  Average        UG
 36     Good        UG
 15     Poor        UG
 32  Average        UG
 25     Good    School,
 '-----------',
 12     No
 46     No
 5     Yes
 45    Yes
 16    Yes
 23     No
 10    Yes
 43     No
 33    Yes
 42    Yes
 44     No
 36    Yes
 15     No
 32    Yes
 25     No
 Name: purchased, dtype: object)

In [7]:
from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], 
                                ['School', 'UG', 'PG']])

oe.fit(x_train)
"""
It learns the structure
It verifies categories exist
It stores the mapping internally
"""

x_train = oe.transform(x_train)
x_test = oe.transform(x_test)

after processing

In [8]:
x_train,"-------------",x_test

(array([[1., 0.],
        [2., 1.],
        [0., 0.],
        [0., 0.],
        [1., 2.],
        [2., 2.],
        [0., 2.],
        [2., 2.],
        [1., 1.],
        [0., 1.],
        [0., 0.],
        [2., 1.],
        [2., 1.],
        [0., 2.],
        [0., 2.],
        [1., 0.],
        [2., 2.],
        [0., 2.],
        [2., 2.],
        [1., 1.],
        [2., 0.],
        [1., 0.],
        [1., 1.],
        [2., 0.],
        [0., 0.],
        [2., 0.],
        [1., 2.],
        [0., 2.],
        [0., 1.],
        [1., 1.],
        [2., 0.],
        [0., 2.],
        [1., 2.],
        [2., 1.],
        [1., 0.]]),
 '-------------',
 array([[0., 0.],
        [0., 2.],
        [1., 0.],
        [0., 2.],
        [0., 1.],
        [2., 0.],
        [2., 1.],
        [0., 2.],
        [2., 2.],
        [2., 2.],
        [1., 1.],
        [2., 1.],
        [0., 1.],
        [1., 1.],
        [2., 0.]]))

In [9]:
oe.categories_ # To se the categories

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

* Use lable encoder for the test data only

In [18]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
le.fit(y_train)
le.classes_

y_train=le.transform(y_train)
y_test=le.transform(y_test)

In [19]:
y_train,"--------------------------",y_test

(array([0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1,
        0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0]),
 '--------------------------',
 array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0]))